### ISSUE TITLE
登录错误

### ISSUE THREAD

**Issue by littlewhitelyw** [coffeehat/BIT-srun-login-script#3]
还没有能力提交PR，只能来提issue了

Step1: Get local ip returned from srun server.
Getting login page
Successfully get login page
Resolving IP from login page html
Successfully resolve IP
----------------
Step2: Get token by resolving challenge result.
Begin getting challenge
Challenge response successfully received
Resolving token from challenge response
Successfully resolve token
----------------
Step3: Loggin and resolve response.
Begin to send login info
Login info send successfully
Resolving login result
Cannot resolve login result. Maybe the srun response format is changed
Traceback (most recent call last):
  File "demo.py", line 6, in <module>
    password = "xxxxxxxxxx"
  File "C:\Users\xxxxxx\Desktop\BIT\BitSrunLogin\LoginManager.py", line 44, in login
    self.get_login_responce()
  File "C:\Users\xxxxxx\Desktop\BIT\BitSrunLogin\LoginManager.py", line 62, in get_login_responce
    self._resolve_login_responce()
  File "C:\Users\xxxxxx\Desktop\BIT\BitSrunLogin\_decorators.py", line 14, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\xxxxxx\Desktop\BIT\BitSrunLogin\_decorators.py", line 32, in wrapper
    outputs = func(self, *args, **kwargs)
  File "C:\Users\xxxxxx\Desktop\BIT\BitSrunLogin\LoginManager.py", line 209, in _resolve_login_responce
    self._login_result = re.search('"suc_msg":"(.*?)"', self._login_responce.text).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by coffeehat** [comment]
收到，这周我看一下
另外如果方便，可否给一份报错位置上`self._login_responce.text`的变量内容？thx~

**Comment by coffeehat** [comment]
你的输出记录看起来token的解析和登录请求的发送都正常，这样第三步的错误可能是两方面导致的：
1. 当前设备你已经登录上校园网了（用填在代码里的账号），这种情况下服务器会返回一个重复登录错误，这个错误我代码里没有写相应的解析，所以会报错。
2. 登录成功返回的信息格式被更新，代码解析不了更新后的信息格式也会报错。

所以建议你先做个测试，大致是这样子：
准备一个电脑，并且确保这台电脑当前没有登录任何校园网账号，然后用这个脚本登录。如果没有报错，并且登录后能正常访问外网，那代码应该就没问题；如果报错，请把报错信息发给我。
另外如果你登录成功，可以尝试再次用脚本登录，可能就能复现你现在遇到的错误。这个错误倒不影响登录过程。

**Comment by littlewhitelyw** [comment]
谢谢如此热情，我刚才又试了一下代码，没有任何问题，是我自己把密码写错了。

我猜你也没想到还有人会把密码写错，所以没有解析这个返回类型

因此报错`Cannot resolve login result. Maybe the srun response format is changed`。

谢谢

**Comment by coffeehat** [comment]
对，我只解析了登录成功的返回，其他各种错误的返回html我都没解析；所以登录不成功时代码就会报错。
当时写的时候只是为了图省事hhhhhh
