### ISSUE TITLE
尝试使用Golang实现模拟登录

### ISSUE THREAD

**Issue by Mmx233** [coffeehat/BIT-srun-login-script#4]
之前一直使用的这个脚本，放在刷了openwrt的路由器上，通电即上网。但是需要在路由器上安装python环境。Go版可以直接编译出相应架构的程序放在外部存储器，从而节约路由器空间。
后来我的新固件超出容量……

https://github.com/Mmx233/BitSrunLoginGo

**Comment by coffeehat** [comment]
可以可以，我一直想用c++写一个呢，看起来不需要了😄
超出容量这种事情，拆焊个容量更大的rom芯片就可以了🤣🤣🤣
