### ISSUE TITLE
group

### ISSUE THREAD

**Issue by JNash123** [coffeehat/BIT-srun-login-script#8]
File "/tmp/net/BitSrunLogin/LoginManager.py", line 92, in _resolve_ip_from_login_page

self.ip = [re.search](http://link.zhihu.com/?target=http%3A//re.search)('name="user_ip" value="(.*?)"', self._page_response.text).group(1)
这个咋解决呀，大佬
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by coffeehat** [comment]
估计是你的页面中没有user_ip这个字段，你可以看看你的页面在返回html时用哪个字段表示ip的

**Comment by coffeehat** [comment]
Closed due to no further discussion
